name: Check Markdown and Examples
on: [push, pull_request]
jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          #cache: npm
      - uses: actions/checkout@v6
      - run: |
          npm install
          npm list
          npm test
